<?php
namespace app\index\controller;
use think\Request;
use think\View;
use think\Controller;

class Index extends Common
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        $request = Request::instance();
        //$request->param();
        $post = $request->except(['user_name']);
        var_dump($post);
        $view = new view();
        return $view->fetch('Index/index');
    }
}
