<?php
namespace app\index\controller;
/**
 * 前台登录控制器
 * Created by PhpStorm.
 * User: baiwei
 * Date: 16/9/23
 * Time: 下午1:23
 */
class Login extends Common{
    public function _initialize(){
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function login(){
        echo 'login';
    }
}